apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: kube:admin
    openshift.io/sa.scc.mcs: s0:c27,c14
    openshift.io/sa.scc.supplemental-groups: 1000730000/10000
    openshift.io/sa.scc.uid-range: 1000730000/10000
  name: CLUSTER_NAME
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
data:
  .dockerconfigjson: PULL_SECRET
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: CLUSTER_NAME
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  ssh-privatekey: SSH_KEY_PRIV
kind: Secret
metadata:
  name: assisted-deployment-ssh-private-key
  namespace: CLUSTER_NAME
type: Opaque
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: CLUSTER_NAME
  namespace: CLUSTER_NAME
spec:
  baseDomain: BASE_DOMAIN
  clusterName: CLUSTER_NAME
  platform:
    agentBareMetal:
      apiVIP: ""
      ingressVIP: ""
      vipDHCPAllocation: "Enabled"
      agentSelector:
        matchLabels:
          bla: aaa
  provisioning:
    imageSetRef:
      name: "4.8"
    sshPrivateKeySecretRef:
      name: assisted-deployment-ssh-private-key
    installStrategy:
      agent:
        sshPublicKey: SSH_KEY_PUB
        networking:
          networkType: OVNKubernetes
          clusterNetwork:
            - cidr: 10.128.0.0/14
              hostPrefix: 23
          serviceNetwork:
            - 172.30.0.0/16
          machineNetwork:
            - cidr: MACHINE_NETWORK_CIDR
        provisionRequirements:
          controlPlaneAgents: 1
          workerAgents: 0
        agentSelector:
          matchLabels:
            bla: aaa
  pullSecretRef:
    name: assisted-deployment-pull-secret
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InstallEnv
metadata:
  name: CLUSTER_NAME
  namespace: CLUSTER_NAME
spec:
  clusterRef:
    name: CLUSTER_NAME
    namespace: CLUSTER_NAME
  sshAuthorizedKeys:
    - SSH_KEY_PUB
  agentLabelSelector:
    matchLabels:
      bla: aaa
  pullSecretRef:
    name: assisted-deployment-pull-secret
