apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
  namespace: assisted-installer
spec:
  storageClassName: ""
  volumeName: PV_AI_POSTGRES
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
